### ISSUE TITLE
is the paper out?

### ISSUE THREAD

**Issue by TracyYXChen** [dmis-lab/VAECox#1]
I didn't find it on arXiv, but I'd like to introduce this ISMB paper to my colleagues. Could you please send it to me if convenient? My email is ychen151@cs.umd.edu Thanks a lot!

**Comment by SunkyuKim** [comment]
I appreciate your interest. I am asking ISMB proceeding management team about uploading the manuscript to preprint servers because of the IP issue. I'll inform you when my manuscript is available.

**Comment by SunkyuKim** [comment]
@TracyYXChen Hi, I am pleased to let you know our paper was published in Bioinformatics.
Please use this [Link](https://doi.org/10.1093/bioinformatics/btaa462) .
Thank you!

**Comment by TracyYXChen** [comment]
congrats!
